simple_votings/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from simple_votings import settings
from vote import views
from vote.views import get_menu_context

urlpatterns = [
    path('', views.index_page, name='index'),

    path('user/', include([
        path('admin/', admin.site.urls),
        path('login/', auth_views.LoginView.as_view(
            extra_context={'menu': get_menu_context(), 'pagename': 'Авторизация'}), name='user.login'),
        path('logout/', auth_views.LogoutView.as_view(), name='user.logout'),
        path('id<int:id>/', views.user, name='user.current'),
        path('registration/', views.registration, name='user.registration'),

        path('password-reset/', auth_views.PasswordResetView.as_view(
            extra_context={'menu': get_menu_context(), 'pagename': 'Сброс пароля'},
            template_name='registration/password/password_reset_form.html',
            email_template_name='registration/password/password_reset_email.html',
        ), name='password_reset'),
        path('password-reset/done/', auth_views.PasswordResetView.as_view(
            extra_context={'menu': get_menu_context(), 'pagename': 'Сброс пароля'},
            template_name='registration/password/password_reset_done.html'
        ), name='password_reset_done'),
        path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
            extra_context={'menu': get_menu_context(), 'pagename': 'Сброс пароля'},
            template_name='registration/password/password_reset_complete.html'
        ), name='password_reset_complete'),
        path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            extra_context={'menu': get_menu_context(), 'pagename': 'Сброс пароля'},
            template_name='registration/password/password_reset_confirm.html'
        ), name='password_reset_confirm'),

        path('profile/', include([
            path('', views.profile, name='profile'),
            path('password-change/', auth_views.PasswordChangeView.as_view(
                extra_context={'menu': get_menu_context(), 'pagename': 'Изменение пароля'},
                template_name='registration/password/password_change_form.html'
            ), name='password_change'),
        ])),
    ])),

    path('voting/', include([
        path('id<int:id>/', views.voting, name='voting.current'),
        path('list/', views.voting_list_page, name='voting.list'),
        path('new/', views.new_voting_page, name='voting.new'),
        path('edit/id<int:id>/', views.edit_voting_page, name='voting.edit'),
    ])),

    path('report/', include([
        path('new_report/', views.new_report_page, name='report.new'),
    ])),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/models.py
from os.path import join

from django.contrib import auth
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView

from vote.utils import get_icon_html, truncate


def _get_url(url):
    def func(self):
        return reverse(url, args=[str(self.id)])

    return func


def _get_html(self, style="text-info", max_len=0):
    return '<a class="{style}" href="{url}">{text}</a>'.format(style=style, url=self.get_url(),
                                                               text=truncate(str(self), max_len))


auth.models.User.add_to_class('get_url', _get_url('user.current'))
auth.models.User.add_to_class('get_html', _get_html)


# ========================= Profile model =========================
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(verbose_name="Аватар", upload_to=join('user_avatars', 'uploads/'),
                               default=join('user_avatars', 'no-image.jpg'), blank=True, null=True)
    biography = models.TextField(verbose_name="О себе", max_length=5000)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


# ========================= Voting models =========================
# for i in range(50): Voting.objects.create(author=User.objects.all()[0], is_open=True, date=timezone.now(), title="TITLE{}".format(i), text='TEXTEXT{}'.format(i), author_visible=0, voting_users_visible=0, result_visible=0)
# Voting.objects.create(author=User.objects.all()[0], is_open=True, date=timezone.now(), title=title, text=text, author_visible=0, voting_users_visible=0, result_visible=0)
class Voting(models.Model):
    author = models.ForeignKey(verbose_name="Автор", to=User, on_delete=models.CASCADE)

    voting_status = (
        (0, 'Закрыто'),
        (1, 'Активно'),
        (2, 'Закончено'),
    )

    status = models.IntegerField(verbose_name='Статус голосования', choices=voting_status)
    date = models.DateTimeField(verbose_name='Время создания')
    title = models.CharField(verbose_name="Заголовок", max_length=100)
    text = models.TextField(verbose_name="Содержание", max_length=5000)

    maximum_votes = models.IntegerField(verbose_name="Лимит голосов", default=100,
                                        validators=[MinValueValidator(0), MaxValueValidator(100)])

    secure_level = (
        (0, 'Видно всем'),
        (1, 'Видно только зарегистрированным пользователям'),
        (2, 'Видно только автору (и администрации)'),
    )

    author_visible = models.IntegerField(verbose_name="Видимость автора", choices=secure_level, default=0)
    voting_users_visible = models.IntegerField(verbose_name="Видимость голосующих", choices=secure_level, default=0)
    result_visible = models.IntegerField(verbose_name="Видимость результатов", choices=secure_level, default=0)

    def get_voted_users(self):
        users = set()
        for item in VotingItem.objects.filter(voting=self):
            for fov in FactOfVoting.objects.filter(voting_item=item):
                users.add(fov.user)
        return list(users)

    def __str__(self):
        return self.title

    @property
    def current_votes(self):
        return len(self.get_voted_users())

    @property
    def current_votes_percent(self):
        if not self.maximum_votes: return 0
        return round(self.current_votes / self.maximum_votes * 100)

    @property
    def is_open(self):
        return self.status == 1

    @property
    def type(self):
        return VotingItem.objects.filter(voting=self)[0].type


Voting.add_to_class('get_html', _get_html)
Voting.add_to_class('get_url', _get_url('voting.current'))


def check_voting(voting):
    if voting.maximum_votes <= 0: return
    if voting.current_votes >= voting.maximum_votes:
        voting.status = 2
        voting.save()

        for u in voting.get_voted_users():
            if u != voting.author:
                end_voting_notification(user=u, voting=voting)
        end_voting_author_notification(voting=voting)


class VotingItem(models.Model):
    voting = models.ForeignKey(verbose_name="Голосование", to=Voting, on_delete=models.CASCADE)
    text = models.TextField(verbose_name="Содержание", max_length=50)

    voting_type = (
        (0, 'Radio Button'),
        (1, 'Check Box'),
    )

    type = models.IntegerField(verbose_name="Тип вопроса", choices=voting_type)

    def is_radio(self):
        return self.type == 0

    def is_combo(self):
        return self.type == 1

    def get_type(self):
        return 'checkbox' if self.type == 1 else 'radio'


class FactOfVoting(models.Model):
    user = models.ForeignKey(verbose_name="Автор", to=User, on_delete=models.CASCADE)
    voting_item = models.ForeignKey(verbose_name="Голосование", to=VotingItem, on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name='Время голосования')

    @property
    def voting(self):
        return self.voting_item.voting


class VotingList(ListView):
    model = Voting


class FactOfVotingList(ListView):
    model = FactOfVoting


# ========================= Other models =========================
class Comment(models.Model):
    user = models.ForeignKey(verbose_name="Автор", to=User, on_delete=models.CASCADE)
    voting = models.ForeignKey(verbose_name="Голосование", to=Voting, on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name='Время создания')
    text = models.TextField(verbose_name="Содержание", max_length=150)


class Report(models.Model):
    user = models.ForeignKey(verbose_name="Автор", to=User, on_delete=models.CASCADE)
    voting = models.ForeignKey(verbose_name="Голосование", to=Voting, on_delete=models.CASCADE)

    report_status = (
        (0, 'В очереди'),
        (1, 'Обработка'),
        (2, 'Закрыто'),
    )

    status = models.IntegerField(verbose_name="Статус", choices=report_status, default=0)
    date = models.DateTimeField(verbose_name='Время создания')
    text = models.TextField(verbose_name="Содержание", max_length=300)


class ReportList(ListView):
    model = Report


class Notification(models.Model):
    user = models.ForeignKey(verbose_name="Пользователь", to=User, on_delete=models.CASCADE)
    voting = models.ForeignKey(verbose_name="Голосование", to=Voting, on_delete=models.CASCADE)

    notification_status = (
        (0, 'Непрочитанное'),
        (1, 'Прочитанное'),
    )

    status = models.IntegerField(verbose_name="Статус", choices=notification_status, default=0)
    date = models.DateTimeField(verbose_name='Время получения')
    html_text = models.TextField(verbose_name="Содержание", max_length=150)
    icon = models.CharField(verbose_name="Иконка", max_length=150, blank=True, default="")


def vote_notification(user, voting):
    ico = 'check-' + ('box' if voting.type == 1 else 'circle')

    if user == voting.author:
        text = 'Вы проголосовали в своём голосовании «{v}».'.format(v=voting.get_html(), )
    else:
        text = 'Вы проголосовали в голосовании «{v}» от {u}.'.format(v=voting.get_html(), u=user.get_html())

    Notification.objects.create(user=user, voting=voting, date=timezone.now(), html_text=text, icon=ico)


def new_voting_notification(voting):
    ico = 'list-' + ('check' if voting.type == 1 else 'ul')

    text = 'Вы создали голосование «{v}».'.format(v=voting.get_html())
    Notification.objects.create(user=voting.author, voting=voting, date=timezone.now(), html_text=text, icon=ico)


def end_voting_notification(user, voting):
    ico = 'x-octagon'
    text = 'Голосование «{v}» от {u}, в котором Вы голосовали, закончено.'.format(
        v=voting.get_html(), u=user.get_html())
    Notification.objects.create(user=user, voting=voting, date=timezone.now(), html_text=text, icon=ico)


def end_voting_author_notification(voting):
    ico = 'x-octagon'
    text = 'Ваше голосование «{v}» закрыто.'.format(v=voting.get_html())
    Notification.objects.create(user=voting.author, voting=voting, date=timezone.now(), html_text=text, icon=ico)

vote/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import formset_factory

from vote.models import Voting, VotingItem, Profile, FactOfVoting, Report


class NewReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = [
            'text',
        ]


class NewVotingForm(forms.ModelForm):
    """
    Класс формы для создания голосования
    """

    class Meta:
        model = Voting  # По образу Voting
        fields = [
            # В форме следующие поля от Voting:
            'title',
            'maximum_votes',
            # 'author_visible',
            # 'voting_users_visible',
            # 'result_visible',
            'text',
        ]


class VotingItemForm(forms.Form):
    text = forms.CharField(
        label="Текст варианта",
        required=True,
        widget=forms.TextInput(
            attrs={
                'required': True,
                'class': 'form-control',
                'placeholder': 'Текст варианта'
            }
        ),
    )

    class Meta:
        model = VotingItem
        fields = ('text',)


VotingItemFormset = formset_factory(VotingItemForm, extra=0)


#   form = CreatingForm()
#   for i in range(n):
#       form.fields['var_' + str(i)] = forms.CharField(
#       label='Вариант ' + str(i + 1),
#       required=True,
#       max_length=VotingItem._meta._forward_fields_map['text'].max_length,
#       )
#  return form

class VoteForm(forms.Form):
    pass


def get_vote_form(voting, user=None):
    form = VoteForm()

    voting_items = VotingItem.objects.filter(voting=voting)
    is_checked = [False for item in voting_items]
    if user:
        if user.is_authenticated:
            is_checked = [bool(FactOfVoting.objects.filter(user=user, voting_item=item)) for item in voting_items]
    already_voted = any(is_checked)
    type = voting_items[0].type

    choices = []
    for index, item in enumerate(voting_items):
        choices.append(("option{}".format(index), item.text))

    if type == 0:
        if not user.is_authenticated:
            form.fields['vote'] = forms.ChoiceField(required=True, widget=forms.RadioSelect(attrs={'disabled': True}),
                                                    choices=choices)
        elif not already_voted:
            form.fields['vote'] = forms.ChoiceField(required=True, widget=forms.RadioSelect, choices=choices)
        else:
            form.fields['vote'] = forms.ChoiceField(required=True, widget=forms.RadioSelect(attrs={'disabled': True}),
                                                    choices=choices, initial="option{}".format(is_checked.index(True)))
    elif type == 1:
        if not user.is_authenticated:
            form.fields['vote'] = forms.MultipleChoiceField(required=True, widget=forms.CheckboxSelectMultiple(
                attrs={'disabled': True}), choices=choices)
        elif not already_voted:
            form.fields['vote'] = forms.MultipleChoiceField(
                required=True, widget=forms.CheckboxSelectMultiple, choices=choices,
                initial=["option{}".format(i) for i in range(len(is_checked)) if is_checked[i]])
        else:
            form.fields['vote'] = forms.MultipleChoiceField(required=True, widget=forms.CheckboxSelectMultiple(
                attrs={'disabled': True}), choices=choices, initial=["option{}".format(i) for i in
                                                                     range(len(is_checked)) if is_checked[i]])
    else:
        raise TypeError
    return form


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email',)


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar',)


class BiographyForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('biography',)


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(label="Аватар", required=False)
    biography = forms.CharField(label="О себе:", max_length=500, widget=forms.Textarea(attrs={"rows": 10, "cols": 20}),
                                required=False)

    class Meta:
        model = Profile
        fields = ('avatar', 'biography',)


class UserNameForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)

vote/templates/pages/index.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col">
            <h1>Главная</h1>
            <hr>
            <i class="glyphicon glyphicon-ok"></i>
            <div class="jumbotron">
                <h1 class="display-4">Приветствуем!</h1>
                <p class="lead">Это простой сайт для простых голосований, созданный по заказу
                    <em>одного человека</em> в учебных целях.</p>
                <hr class="my-4">
                <p>Вы можете посмотреть активные в данный момент голосования.</p>
                {% if not user.is_authenticated %}
                    <p>Если Вы <a href="{% url 'user.registration' %}">зарегиструйтесь</a> или
                        <a href="{% url 'user.login' %}">войдёте</a>, то можете создавать голосования
                        и голосовать в уже существующих</p>
                {% else %}
                    <p>Вы также можете создать своё голосование или проголосовать в уже существующем.</p>
                {% endif %}
                <div class="form-inline mt-4">
                    <a class="btn btn-primary btn-lg mr-3" href="{% url 'voting.list' %}" role="button">Активные голосования</a>
                    <a class="btn btn-outline-primary btn-lg" href="{% url 'voting.new' %}" role="button">Создать своё голосование</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

vote/templates/pages/report-new.html
{% extends 'base/base.html' %}

{% load bootstrap4 %}


{% block content %}
<h1>Новая жалоба</h1><hr>
    <div class="row">
        <div class="col">
            {% if not voting_id %}
                <div class="h3 text-muted font-italic text-center">
                    Вообще-то тут не стоит находиться.<br>
                    <a href="{% url 'index' %}">Идити-ка отсюда</a>
                </div>
            {% else%}
                {% if not voting %}
                    <div class="h3 text-muted font-italic text-center">
                        Кажется, что-то пошло не так, и мы потеряли ваше голосование.<br>
                        <a href="{% url 'voting.list' %}">К списку</a>
                    </div>
                {% else %}
                    <h3 class="text-center">Новая жалоба на голосование «{{ voting.get_html|safe }}» автора {{ voting.author.get_html|safe }} от <a class="text-muted">{{ voting.date }}</a></h3>
                    <form action="{% url 'report.new' %}" method="post">
                        {% csrf_token %}

                        {% bootstrap_form form %}

                        <input type="hidden" name="voting_id" value="{{ voting_id }}">
                        <input type="submit" class="btn btn-primary float-right btn-block mt-4" value="Отправить">
                    </form>
                {% endif %}
            {% endif %}
        </div>
    </div>

{% endblock %}

vote/templates/pages/voting-current-form-disabled.html
{% load contains_tag %}

<div class="form-group" >
{% for f in form.vote %}
    <div class="custom-control custom-{{ form_type_text }}">
        {% if form.vote.initial and 'option'|str_add:forloop.counter0|contains:form.vote.initial %}
            <input type="{{ form_type_text }}" id="option{{forloop.counter}}" name="vote" value="option{{forloop.counter0}}" class="custom-control-input" checked disabled>
        {% else %}
            <input type="{{ form_type_text }}" id="option{{forloop.counter}}" name="vote" value="option{{forloop.counter0}}" class="custom-control-input" disabled>
        {% endif %}
        <label class="custom-control-label" for="option{{forloop.counter}}">{{ f.choice_label }}</label>
    </div>
{% endfor %}
</div>

vote/templates/pages/voting-current.html
{% extends 'base/base.html' %}

{% load bootstrap4 %}
{% load static %}
{% load icon_tag %}


{% block extra_js %}
<script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
<script type='text/javascript' src="{% static 'scripts/voting_chart.js' %}"></script>
<script type="text/javascript">$(document).ready(function() {gen_voting_chart({{ chart_labels|safe }}, {{ chart_values|safe }});});</script>
{% endblock %}


{% block content %}
    {% if found %}
        <div class="row">
            <div class="col">
                <a class="h1">Голосование</a>
            </div>
            <div class="col">
                {% if voting.author == request.user %}
                    <form class="form-inline" method="POST" action="">
                        {% csrf_token %}
                        <a href="#" class="badge btn btn-outline-danger ml-auto font-weight-normal mt-3" data-toggle="modal" data-target="#remove_modal">{% icon "trash" 24 %}<c class="mr-1">Удалить</c></a>
                        <div class="modal fade" id="remove_modal" tabindex="-1" role="dialog" aria-labelledby="remove_modalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                          <h5 class="modal-title" id="remove_modalLabel">Подтвердите удаление</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                              <span aria-hidden="true">&times;</span>
                                          </button>
                                      </div>
                                      <div class="modal-body text-center">
                                          Вы уверены, что хотите удалить своё голосование?<br> Это действие невозможно будет отменить!
                                      </div>
                                      <div class="modal-footer">
                                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                                          <input type="submit" class="btn btn-danger" name="remove_submit" value="Удалить!">
                                      </div>
                                </div>
                            </div>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-4">
                <div class="card h-100">
                    <div class="card-header">
                        <a class="text-secondary font-italic">{% icon 'info' 24 %} Информация</a><a class="badge btn btn-outline-danger float-right font-weight-normal p-0" href="{% url 'report.new' %}?voting_id={{ voting.id }}">{% icon "alert-triangle" 24 %} <c class="mr-1">Пожаловаться</c></a>

                    </div>
                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-sm-6">Автор:</dt>
                            <dd class="col-sm-6">
                                <a href="{{ voting.author.get_url }}">{{ voting.author }}</a>
                                <!--{% if can_see_author %}-->
                                <!--{% else %}-->
                                <!--<em>???</em>-->
                                <!--{% endif %}-->
                            </dd>

                            <dt class="col-sm-6">Дата создания:</dt>
                            <dd class="col-sm-6">{{ voting.date }}</dd>

                            <dt class="col-sm-6">Статус:</dt>
                            <dd class="col-sm-6"><em>{{ voting.get_status_display }}</em></dd>

                            <!--<dt class="col-sm-6">Видимость автора:</dt>-->
                            <!--<dd class="col-sm-6">{{ voting.get_author_visible_display }}</dd>-->

                            <!--<dt class="col-sm-6">Видимость голосущих:</dt>-->
                            <!--<dd class="col-sm-6">{{ voting.get_voting_users_visible_display }}</dd>-->

                            <!--<dt class="col-sm-6">Видимость результатов:</dt>-->
                            <!--<dd class="col-sm-6">{{ voting.get_result_visible_display }}</dd>-->

                            <dt class="col-sm-6">Голоса:</dt>
                            <dd class="col-sm-6">
                                {{ voting.current_votes }}
                                {% if voting.maximum_votes %}
                                / {{ voting.maximum_votes }}
                                {% endif %}
                            </dd>
                        </dl>
                        {% if voting.maximum_votes %}
                        <div class="progress mb-3">
                            <div class="progress-bar progress-bar-striped" role="progressbar"
                                 aria-valuenow="{{ voting.current_votes }}" aria-valuemin="0"
                                 aria-valuemax="{{ voting.maximum_votes }}"
                                 style="width: {{ voting.current_votes_percent }}%">{{ voting.current_votes_percent }}%</div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card box-shadow h-100">
                    <div class="card-header">
                        <div class="text-secondary font-italic">{% if vote.type == 1 %}{% icon "check-box" 24 %}{% else %}{% icon "check-circle" 24 %}{% endif %} Голосовать</div>
                    </div>
                    <div class="card-body d-flex flex-column">
                        {% if not user.is_authenticated %}
                            {% include 'pages/voting-current-form-disabled.html' %}
                            <input type="submit" class="align-self-end btn btn-outline-primary btn-block mt-auto" value="Войдите, чтобы голосовать" disabled>
                        {% elif voting.status != 1 %}
                            {% include 'pages/voting-current-form-disabled.html' %}
                            <input type="submit" class="align-self-end btn btn-outline-dark btn-block mt-auto" value="Голосование недоступно" disabled>
                        {% elif user in voting.get_voted_users %}
                            {% include 'pages/voting-current-form-disabled.html' %}
                            <input type="submit" class="align-self-end btn btn-outline-success btn-block mt-auto" value="Вы уже проголосовали" disabled>
                        {% else %}
                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="form-group" >
                                {% for f in form.vote %}
                                    <div class="custom-control custom-{{ form_type_text }}">
                                        <input type="{{ form_type_text }}" id="option{{forloop.counter}}" name="vote" value="option{{forloop.counter0}}" class="custom-control-input">
                                        <label class="custom-control-label" for="option{{forloop.counter}}">{{ f.choice_label }}</label>
                                    </div>
                                {% endfor %}
                                </div>
                                <input type="submit" class="align-self-end btn btn-primary btn-block mt-auto" name="vote_submit" value="Голосовать!">
                            </form>
                        {% endif %}
                        <!--{% if "option1" == form.vote.initial %}-->
                            <!--<p>asd{{ form.vote.initial }}</p>-->
                        <!--{% endif %}-->
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <div class="card-header">
                        <div class="text-secondary font-italic">{% icon 'pie-chart' 24 %} Диаграмма</div>
                    </div>
                    <div class="card-body chart-container">
                        <canvas id="voting_chart"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <a class="text-secondary font-italic">{% icon 'document-text' 24 %} Содержание голосования</a>
                        {% if voting.author == request.user %}
                            {% if can_be_edited %}
                                <a href="{% url 'voting.edit' id=voting.id %}" class="badge btn btn-outline-info float-right font-weight-normal p-0">{% icon "pencil" 24 %} Изменить</a>
                            {% else %}
                                <span class="d-inline-block float-right" tabindex="0" data-toggle="tooltip" title="Редактировать можно до первого голоса">
                                    <button class="badge btn btn-outline-info p-0" style="pointer-events: none;" type="button" disabled><del class="mr-1">{% icon "pencil" 24 %} Изменить</del></button>
                                </span>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ voting.title }}</h5>
                        <p class="card-text">{{ voting.text|linebreaks }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <h1>Голосование</h1>
        <hr>
        <h3 class="text-muted text-center">
            <em>Голосование не найдёно.<br>
                <a href="{% url 'index' %}">На главную</a>
            </em>
        </h3>
    {% endif %}
{% endblock %}

vote/templates/pages/voting-edit.html
{% extends 'base/base.html' %}

{% load bootstrap4 %}
{% load static %}


{% block extra_js %}
<script type='text/javascript' src="{% static 'scripts/formset.js' %}"></script>
{% endblock %}

{% block content %}
<h1>Редактирование голосования</h1>
<hr>
{% if not found %}
    <h3 class="text-muted text-center">
        <em>Голосование не найдёно.<br>
            <a href="{% url 'index' %}">На главную</a>
        </em>
    </h3>
{% elif not can_be_edited%}
    <h3 class="text-muted text-center">
        <em>Голосование уже нельзя редактировать.<br>
            <a href="{% url 'index' %}">На главную</a>
        </em>
    </h3>
{% else %}
    <div class="row">
        <div class="col">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form voting_form %}

                <h2 class="mt-4">Варианты ответов голосования</h2>
                <hr>
                {% bootstrap_formset_errors formset %}
                {{ formset.management_form }}
                {% for form in formset %}
                    <div class="row form-row spacer mb-2">
                        <div class="col-2">
                            <label>{% bootstrap_label form.text.label %}</label>
                        </div>
                        <div class="col">
                            <div class="input-group">
                                {% bootstrap_field form.text show_label=False form_group_class='' %}
                                <div class="input-group-append">
                                    <a class="btn btn-success add-form-row text-white">+</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <input type="hidden" name="type" value="{{ voting_type }}">
                <input type="submit" class="btn btn-primary float-right btn-block mt-4" value="Изменить!">
            </form>
        </div>
    </div>
{% endif %}
{% endblock %}